[tool.poetry]
name = "torchmanager-diffusion"
version = "1.3a8"
description = "Torchmanager Implementation for Diffusion Model (v1.3 Alpha 8)"
authors = ["Kison Ho <unfit-gothic.0q@icloud.com>"]
packages = [
    { include = "diffusion" },
    { include = "diffusion_bridges" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
einops = "*"
torchmanager = { version = "^1.5b1", optional = true }
torchvision = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
